### ISSUE TITLE
Suggestion: add toggle as either keybind or modmenu setting

### ISSUE THREAD

**Issue by Sea-Kerman** [AzureDoom/I-See-Lava#1]
It would be nice if you could easily toggle between vanilla and transparent.

**Comment by Sea-Kerman** [comment]
hmm, actually, looking at the implementation it might be easiest to just include a "vanilla lava" resource pack. It seems to mostly work (though it makes lava brighter than vanilla with my shaders)

**Comment by Sea-Kerman** [comment]
normal lava with shaders
![2022-09-08_09 27 57](https://user-images.githubusercontent.com/41390862/189210387-058da549-d84d-4686-93c6-9fac9d68f54c.png)

transparent lava with opaque resource pack with shaders
![2022-09-08_09 26 12](https://user-images.githubusercontent.com/41390862/189210424-da54c74c-11ca-47db-8e15-565a0344dda2.png)

**Comment by Sea-Kerman** [comment]
aha, I fiddled around a bit and if you make it GetCutout() instead of translucent then you can get a similar effect while being able to turn it off with a resource pack and not mess with shader brightness

"turn it off" resource pack off
![2022-09-08_12 31 06](https://user-images.githubusercontent.com/41390862/189210822-4843b801-d09a-4274-b1e0-c3e9006275c3.png)

"turn it off" resource pack on
![2022-09-08_12 31 33](https://user-images.githubusercontent.com/41390862/189210913-55848cda-a398-422d-a8a4-0d99f57dcdef.png)

**Comment by AzureDoom** [comment]
I won't have time to work on this for a bit, but free to send a PR if you'd like!

**Comment by Sea-Kerman** [comment]
hmm, we can either have them separately download the "turn it off" resource pack or have it come with the mod but then we need to depend on fabric API

**Comment by AzureDoom** [comment]
That's fine with me
