### ISSUE TITLE
Lava looks broken on v.1.1.0

### ISSUE THREAD

**Issue by thepan2b** [AzureDoom/I-See-Lava#3]
Minecraft 1.19.2
On both [1.19.2] Fabric API 0.60.0+1.19.2 and [1.19.2] QFAPI 4.0.0-beta.11 and QSL 3.0.0-beta.15 on both Fabric and Quilt loader
![image](https://user-images.githubusercontent.com/113259791/189497231-a1c0dda5-c9c4-4227-afd0-ae85e65d4d57.png)

v1.0.0 worked fine

**Comment by AzureDoom** [comment]
The texture changed this is why
