### ISSUE TITLE
[URGENT] [BUG] Could not execute entrypoint stage 'client' due to errors, provided by 'iseelava'!

### ISSUE THREAD

**Issue by NopeProsOnly** [AzureDoom/I-See-Lava#5]
https://paste.gg/p/anonymous/6147bf7116d140bbb30a320afd1671b8

The launcher has updated. With that update, they made accessibility settings more accessible. This means that the first screen you see isn't the main menu. I don't know if this is related, but may help.

**Comment by AzureDoom** [comment]
This is an issue with reimaginedmenus, not this mod.
